diger implementation
WebOfTrust/cesride pull request #30
Opened 2023-01-25 10:59 UTC by jasoncolburne

# Rationale
`Diger` is built upon `Matter` and hashing algorithms alone. It was a pretty simple next step after implementing `Matter`.

# Testing
Pretty complete this time, though I didn't examine the KERIpy tests. The code was so simple I merely exhausted the primary control flows. The digest tests ensure we don't mismatch an algorithm, they aren't intended to test the hasing functions themselves.

# Notes
With 512-bit digests, ahead of KERIpy.

2023-01-25 14:50 UTC, m00sey requested changes
We should include at least one test vector from keripy, it's been our "measure of interoperability" so far.

https://github.com/WebOfTrust/keripy/blob/5a19417a3c6e79e868ae96f55e82385de0c348d3/tests/core/test_coring.py#L4167

2023-01-25 21:48 UTC, jasoncolburne commented
> We should include at least one test vector from keripy, it's been our "measure of interoperability" so far.

I'll do this tonight

2023-01-26 09:33 UTC, jasoncolburne commented
I added the most comprehensive python test and fixed a bunch of stuff in Matter. Let me know if you want to go through anything I did. Basically, we were passing things by value and doing a lot of unnecessary clones and conversions. It broke down when the test code got more complex and needed to reuse borrowed values.

2023-01-26 09:36 UTC, jasoncolburne commented on src/lib.rs
> +//#![deny(elided_lifetimes_in_paths)]
Whoops, this comment is unintentional. Let me remove that.

2023-01-26 12:55 UTC, m00sey approved these changes
lgtm

Some of those extra clones were definitely me trying to fix compilation errors around borrowing etc, you're changes make a  lot of sense so thanks for cleaning it up.

2023-01-26 12:58 UTC, merged